### ISSUE TITLE
Unable to login to BC Registration

### ISSUE THREAD

**Issue by swcurran** [bcgov/ised-business-banking-initiative#20]
Please review the deployment of this URL: https://bcreg-registration-issuer.apps.silver.devops.gov.bc.ca/

Why after clicking "Agree" (after checking the checkbox) we get a page with an `{"error":"invalid_client"}` error.  Looks like perhaps something with the SSO config is wrong?  URL issue?

Here is where we are getting the error: https://toip-vc-authn-controller.apps.silver.devops.gov.bc.ca/vc/connect/authorize?scope=openid+vc_authn&state=LftrR1-HY0lbIAvGFnWx9WH8L2WBRyAUGcEvya79se4.u1BqGsXBRrg.bcreg-registration-issuer&response_type=code&client_id=gzyg46lx-prod&redirect_uri=https%3A%2F%2Foidc.gov.bc.ca%2Fauth%2Frealms%2Fgzyg46lx%2Fbroker%2Fverifiable-credential%2Fendpoint&pres_req_conf_id=citz-verified-person&nonce=-3TebEiW6z19A9XBFEPhgA

**Comment by swcurran** [comment]
Assigning to @WadeBarnes , but FYI @esune .

**Comment by WadeBarnes** [comment]
This issue has been resolved.
