### ISSUE TITLE
Update the deployment and test to get working with the Trinisic Wallet

### ISSUE THREAD

**Issue by swcurran** [bcgov/ised-business-banking-initiative#25]
I've noticed that the deployment is not working on production with the Trinisic Wallet.  Please go through the deployment and try to figure out why it is not working with that wallet. Here is the set of production URLs:

* Get the Trinisic Wallet and initialize
* In the settings, for "Network", pick "Sovrin Staging"
* https://bcgov-citz-issuer.apps.silver.devops.gov.bc.ca/
  * Use the "Test Services Card" for authentication and "DIACC1001" and "98901" for testing (can also use 2, 3, 4, 5 for the last digits)
  * Fill in missing data (DoB, email, Gender -- I think that is all)
     * Bug: When I went in I found some fields that should have been empty were filled in (e.g. email address).
       * Seems like data from another session is being picked up?
       * To test this -- hit "Submit" without filling in anything to see what fields are empty -- should be the same everytime
  * Get a VP credential
* https://bcreg-registration-issuer.apps.silver.devops.gov.bc.ca/
  * Authentication: Presentation request for data from the VP credential
     * Issue: Sometimes this doesn't work -- seems VP is still in "Pending" state until I look at the credential.
  * Fill in more data -- any fields that are empty
  * Get the VO credential
     * Issue: This is the point the demo fails -- the connection is made and the Credential Offer sent, but nothing happens on the Mobile side.
* https://bcreg-relationship-issuer.apps.silver.devops.gov.bc.ca/
     * Authentication: Presentation request for data from the VP and VO credentials
     * Fill in data
     * Get the VR credential
* https://business-bank-verifier.apps.silver.devops.gov.bc.ca/
     * Authentication: Presentation request for data from the VP, VO and VR credentials
     * Done!!

Note that I tried this with the BC Wallet as well, and it also failed at the same point -- getting the VO credential from the second Issuer Kit instance.

**Comment by wadeking98** [comment]
now that we've determined this to be an issue intrinsic to trinsic, can I close this issue @swcurran?

**Comment by swcurran** [comment]
Assign it to me for now.  As long as it's stable with wallets it is working with -- all good.

I need to review the data from the Trinsic wallet that you sent me.

**Comment by swcurran** [comment]
Overcome by events. Closing.
