### ISSUE TITLE
Update the Schema and Presentation Requests for VP, VO and VR on this deployment

### ISSUE THREAD

**Issue by swcurran** [bcgov/ised-business-banking-initiative#26]
This deployment uses three schemas that were defined at the ISED Business Banking Initiative level in the early days of the project.  Recently, a new version of the Schemas has been defined.  We need to update the Schemas to the new ones.  That will include:

* Getting the new Schema defined in the config for this repo and published on the appropriate ledgers.
* Updating the default values that are being used to populate the SurveyJS forms for specific values.
   * Fields are populated via: data from the authentication process, populated by code snippets, typed in by the user.
   * Some of the existing fields will go away, others added and will need to be populated from a code snippet.
   * Note that some fields will just be renamed and in that case, the way the field is populated will remain the same.
* The presentation requests will need to be updated to reflect the schema fields added or removed.

I'm working on the getting a list of the new fields and from there the delta between the old and new. This will include the attributes removed, renamed. left the same and added.

Heads up @wadeking98 -- this will be coming your way Real Soon Now.

**Comment by swcurran** [comment]
Here is what needs to be done, based on this [Mapping document](https://docs.google.com/spreadsheets/d/1qZBI8flpY9FTNGN9DBevqHGnO1FJNAxt8f51eEhFvuI/edit?usp=sharing) that defines the old schema, the new schema and how to get from the old to the new.  These are the steps that I think are needed:

1. Update the schema objects (VP, VO and VR) with the new fields and with a new version ID, publish to the ledger with new CredDefs using the new schemas.  When published, update this ticket with the ledger, identifiers and (if possible) a link to each object on a browser (such as [IndyScan](indyscan.io) for the prod instance objects on Sovrin Staging).
2. Update the presentation requests to either remove or update the claim names to be pulled.  In some cases (e.g. for presentation requests pulling from VP), some claim names need to be added.
3. Update the SurveyJS elements (aka VC to be issued) as needed (e.g. remove, rename, add new elements), to use the renamed presentation claims and to generate new hardcoded values.  I'm not certain how that is done, but the mapping document should provide adequate details.
4. Update the Banking Presentation request to pull all the necessary data from the source VCs (all of VP, VO and VR).

Questions may come up along the way, but I think this should be a good start.  Please post in this ticket as you may progress, come across questions and need testing done.

Thanks!

Assigning this to @wadeking98 to have fun with! :-)

**Comment by swcurran** [comment]
Testing on dev -- I found these issues so far:

- Verified Person
  - The "Additional Names" field should have been picked up from the "givenNames" (I think) claim in the authentication token
  - The email address is being picked up from somewhere -- not sure where or how. It's mine, but how does the service know?  It's not in the authentication claim.
  - Issuing failed.  I got an "unknown message" error in the Trinsic wallet.

Perhaps a reset is needed?

**Comment by swcurran** [comment]
OK -- ran through with test and things are generally looking good.  Some things:

- Could we have a convention where a special magic value in the SurveyJS fields gets converted to "" after process?  For example, if we put "--" into a field, a post surveyJS step converts that to ""?  Perhaps a question for Emiliano.  If we can do that, we would change some of the values.
- The CredDef is "default" for each of the credentials, but should be "verifiedPerson", verifiedOrganization" and "verifiedRelationship".  Please make that change.  Currently: rcruXFgWnAXH44ofKfaRQ:3:CL:288922:default
- Change the hardcode "Title" to "Sits **on** the Board..." instead of "at"
- Change the business bank visual verifier to ONLY ask for the address fields from the VO, not from the VP

**Comment by swcurran** [comment]
None of these ^^^^ are crucial. If you think that can be done quickly, go for it. Otherwise, just promote to prod and look at them after.

Let me know on the first one.  I'd like to use that if we can.

**Comment by wadeking98** [comment]
@swcurran for `issuer` we have 3 duplicates in the bcBank verifier page: `['BC', 'BC Registries', "Ministry of Citizens' Services"]` do we need all these or should the proof request only ask for the `Verified Organization` issuer?

**Comment by swcurran** [comment]
Two answers.  First, set the "issuer" to "BC" for all of the credentials in the respective issuer kit instances.  Second, leave this as is, with the three issuers showing up.  I think this is OK for this claim vs. the address duplicates.

**Comment by wadeking98** [comment]
Change completed:
![image](https://user-images.githubusercontent.com/36937407/164066479-7695db92-58ed-45b3-b9c0-32269e56e7ca.png)
